### ISSUE TITLE
Date in string format doesn't work, and prevent error doesn't work

### ISSUE THREAD

**Issue by dsilva01** [IonicaBizau/clone-date#14]
> > ```js
> > const cloneDate = require("clone-data")
> > 
> > console.log(cloneDate("1970-05-10")); 
>>
> > console.log(cloneDate("dfs"));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The expected output is `the Date`, as `1970-05-10` is a date. It logs `Error` instead.
> > The expected output is `Invalid Date`, as `dfs` is a string. It logs `Error` instead.

**Comment by servusdei2018** [comment]
cloneDate doesn't accept a string parameter, but rather a Date parameter:
https://github.com/IonicaBizau/clone-date/blob/c87eb29bda722ea189c6c99ff559f195b25c4502/lib/index.js#L7

You are getting an error because you are calling it incorrectly.
